"""Smoke test: prove the Notion connection works before building anything else.

Run after filling .env and finishing srujit/NOTION_SETUP.md:
    python scripts/test_notion.py

It creates ONE task in your database. If it succeeds, plumbing is good.
"""
from datetime import date

from app.schemas.models import ActionItem, OwnerStatus
from app.integrations.notion import push_action_item

if __name__ == "__main__":
    item = ActionItem(
        task="✅ Notion connection test — safe to delete",
        owner="Test User",
        owner_status=OwnerStatus.RESOLVED,
        deadline=date.today(),
        source_quote="Generated by scripts/test_notion.py",
        confidence=1.0,
    )
    page_id = push_action_item(item, meeting_label="connection-test")
    print(f"Success! Created Notion page: {page_id}")
    print("Open your Notion database — you should see the test task.")
